language: scala
sudo: false
jdk:
  - oraclejdk8
script:
  - sbt +test +publishLocal plugin/test plugin/scripted
  - cd docs && sbt test validateDocs
cache:
  directories:
    - $HOME/.ivy2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
